name: Lint

on: [pull_request]

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Cache the dependency directories
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('*.json') }}

      - name: Install dependencies with npm
        run: npm install --save-dev

      - name: Lint with npm
        run: npm run lint
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup default stable
          rustup component add clippy
        shell: bash

      - name: Cargo lint
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: cargo clippy --all -- -D warnings
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
         version: latest
         working-directory: v2
